package cn.amazon.aws.rp.spapi.enums;

public enum NotificationType {
//    SQS
    ANY_OFFER_CHANGED,
    FEED_PROCESSING_FINISHED,
    FBA_OUTBOUND_SHIPMENT_STATUS,
    FEE_PROMOTION,
    FULFILLMENT_ORDER_STATUS,
    REPORT_PROCESSING_FINISHED,

//    Eventbridge
    BRANDED_ITEM_CONTENT_CHANGE,
    ITEM_PRODUCT_TYPE_CHANGE,
    MFN_ORDER_STATUS_CHANGE,
    B2B_ANY_OFFER_CHANGED
}
