package cn.amazon.aws.rp.spapi.enums;

/**
 * @description:
 * @className: ReportTypeEnum
 * @type: JAVA
 * @date: 2020/11/10 20:02
 * @author: zhangkui
 */
public enum ReportTypeEnum {
	/*** FBA Amazon Fulfilled Shipments Report */
	_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_,
	/*** FBA Amazon Fulfilled Shipments Report */
	GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL,

	GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE,

	GET_ORDER_REPORT_DATA,

	GET_CONVERGED_FLAT_FILE_ORDER_REPORT_DATA,

	GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA,

	GET_FBA_MYI_ALL_INVENTORY_DATA,

	GET_FLAT_FILE_OPEN_LISTINGS_DATA,

	GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA, //amzn1.tortuga.3.f2639dc4-9267-4881-853a-6a031dc5ecc0.T2YPPW67JP3FM9

	GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE,


}
